# Generated by Django 3.2.13 on 2022-05-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_vantagem_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='vantagem',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
