# Generated by Django 3.2.13 on 2022-05-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_vantagem_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vantagem',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
