# Generated by Django 3.0.8 on 2022-05-22 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='saldo',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_enviado', models.IntegerField()),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinario', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remetente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'extrato',
            },
        ),
    ]
